import io
import markdown
import matplotlib.pyplot as plt
from fpdf import FPDF
import tempfile
import os
import re

class CyberFusionPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 15)
        self.set_fill_color(30, 41, 59) # Slate 800
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, "CyberFusion AI - Security Investigation Report", border=0, align="C", fill=True)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by CyberFusion AI SOC Agents", align="C")

def generate_severity_chart(report_text: str) -> str:
    """Generates a gauge or bar chart based on severity and returns temp file path."""
    severity_match = re.search(r"(?:severity|risk)\s*(?::|rating|level)?\s*:?\s*(critical|high|medium|low)", report_text, re.IGNORECASE)
    severity = severity_match.group(1).lower() if severity_match else "unknown"
    
    levels = {"low": 1, "medium": 2, "high": 3, "critical": 4, "unknown": 0}
    val = levels.get(severity, 0)
    
    colors = {"low": "#05c280", "medium": "#facc15", "high": "#fb923c", "critical": "#ef4444", "unknown": "#64748b"}
    color = colors.get(severity, colors["unknown"])
    
    fig, ax = plt.subplots(figsize=(6, 1.5))
    ax.barh(["Severity"], [val], color=color, height=0.5)
    ax.set_xlim(0, 4)
    ax.set_xticks([0, 1, 2, 3, 4])
    ax.set_xticklabels(["Unknown", "Low", "Medium", "High", "Critical"])
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.margins(y=0.1)
    
    # Save chart to temp file
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
    plt.tight_layout()
    plt.savefig(temp_file.name, bbox_inches='tight', dpi=150)
    plt.close(fig)
    return temp_file.name

def generate_pdf(report_markdown: str, report_type: str = "Technical") -> bytes:
    """Generates a branded PDF containing the markdown report."""
    pdf = CyberFusionPDF()
    pdf.add_page()
    
    # Add Chart
    try:
        chart_path = generate_severity_chart(report_markdown)
        pdf.image(chart_path, x=75, y=25, w=60)
        os.unlink(chart_path)
        pdf.ln(30)
    except Exception as e:
        print(f"Failed to generate chart: {e}")
        pdf.ln(5)
    
    # Title
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, f"{report_type.title()} Report", align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Clean GitHub flavor markdown for HTML conversion
    cleaned_markdown = re.sub(r'> \[!.*?\]', '>', report_markdown)
    
    # Convert MD to HTML
    html_content = markdown.markdown(cleaned_markdown, extensions=['tables'])
    
    # Ensure PDF writes HTML
    pdf.set_font("helvetica", size=11)
    pdf.set_text_color(51, 65, 85)
    
    try:
        pdf.write_html(html_content)
    except Exception as e:
        print(f"HTML rendering failed: {e}. Falling back to text.")
        pdf.multi_cell(0, 6, text=cleaned_markdown)
        
    return pdf.output()
